import type { Metadata } from "next";
import "./globals.css";
import GradualBlur from "./components/layout/gradual";
import Navbar from "./components/layout/Navbar";
import AOSInitializer from "./components/layout/AOSinitializer";
import { Outfit } from "next/font/google"; // ✅ import font

// Setup Outfit
const outfit = Outfit({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* ✅ apply Outfit ke body */}
      <body className={outfit.className}>
        {/* Jalankan AOS */}
        <AOSInitializer />

        <section className="relative min-h-screen overflow-hidden bg-black">
          <div className="h-full">
            <Navbar />
            <div className="mb-10"></div>
            {children}
          </div>

          {/* Gradual Blur fixed di bottom */}
          <div className="fixed bottom-0 left-0 w-full pointer-events-none">
            <GradualBlur
              target="parent"
              position="bottom"
              height="3rem"
              strength={2}
              divCount={5}
              curve="bezier"
              exponential={true}
              opacity={1}
            />
          </div>
        </section>
      </body>
    </html>
  );
}
